### PR TITLE
BASIC-1215: Views alter to add event series column on manage events tabl...

### PR DESCRIPTION
**Pull request by sherakama**
...e

### CODE REVIEW

**Comment by sherakama** [comment]
@cjwest,
Please review. 

*\* To test
- Build latest development JSA
- Checkout basic-1215 branch
- Clear caches
- view admin/manage/events

It should look something like this:
screen shot 2015-03-16 at 3 09 05 pm

**Comment by sherakama** [comment]
@cjwest ,

_nudge_ This is blocking me on the 4.4 release

**Comment by cjwest** [comment]
Very nice, Shea!  I like that you've included sample content!

**Comment by sherakama** [comment]
Thank you.

**Pull request merged**
